development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: supercampeones
  password: benjiprice
  database: supercampeones_development
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: supercampeones
  password: benjiprice
  database: supercampeones_test
  host: localhost
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: supercampeones
  password: benjiprice
  database: supercampeones_production
